# https://github.com/marketplace/actions/deploy-to-github-pages
name: Build and Deploy
# on: [push]
on:
  push:
    branches:
      - test/docsSDK
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2 
      actions: write     
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # uses: actions/checkout@v2.3.1
        uses: actions/checkout@v2.4.0

      - name: Build SDK Docs # This is built using npm and outputs the result to the 'help' folder. 
        run: |
          npm ci
          npm run help

      - name: Deploy to GitHub Pages
        # uses: JamesIves/github-pages-deploy-action@4.1.8
        uses: JamesIves/github-pages-deploy-action@4.2.0        
        with:
          
          # token: ${{ secrets.API_TOKEN_DOCS }}          
          github-token: ${{ secrets.action-token-docs-full }}

          # Deploy From (GitHub Actions environment):
          folder: help # GSF SDK folder docs put into
          # Deploy To:
          repository-name: geospatial-services-framework/geospatial-services-framework.github.io
          # branch: master # The branch the action should deploy to.
          branch: testing # The branch the action should deploy to.          
          target-folder: sdk-docs # The folder the action should deploy to.
          clean: false # Whether to clean the folder before deploying.
          commit-message: "Testing"

          #force test/docsSDK